# Generated by Django 5.2.17 on 2026-09-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Miscellaneous', 'Miscellaneous')], max_length=20),
        ),
    ]
