# Generated by Django 5.2.17 on 2026-09-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_budget_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
