# Generated by Django 5.2.17 on 2026-09-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_savingsgoal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('budget', 'Budget Limit Alert'), ('savings', 'Savings Goal Milestone'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
